-- 1

SELECT 
    OFICIO.proyectos2020,
    SUM(SUELDO) AS "SUELDO TOTAL"
FROM 
    FUNCIONARIOS
WHERE 
    IDOFI = (SELECT IDOFI FROM OFICINAS WHERE NOMBREOFI = 'VENTAS')
GROUP BY 
    OFICIO;
