select count(*) 
from enemdu
where edad  between 40 and 65 

select * 
from enemdu;

create index ENEMDU_EDAD_IDX ON ENEMDU(EDAD);

select count(*) 
from enemdu
where CANTON = '1701';

create index ENEMDU_CANTON_IDX ON ENEMDU(CANTON);
drop INDEX ENEMDU_CANTON_IDX;


select count(*) 
from enemdu
where NIVEL_DE_INSTRUCCION  = '06 - Secundaria' 
    and ETNIA = '6 - Mestizo';
    
create index ENEMDU_NIVELEINS_ETNIA_IDX ON ENEMDU(NIVEL_DE_INSTRUCCION, ETNIA);



SELECT RAMA_ACTIVIDAD, COUNT(*)
FROM ENEMDU
WHERE RAMA_ACTIVIDAD IS NOT NULL
GROUP BY RAMA_ACTIVIDAD 

CREATE INDEX ENEMDU_RAMA_ACTIVIDAD_IDX ON ENEMDU(RAMA_ACTIVIDAD);

SELECT COUNT (*)
FROM ENEMDU
WHERE UPPER(SUBSTR(GRUPO_OCUPACION,6)) LIKE 'TRABAJA%' 

CREATE INDEX ENEMDU_GRUPOOCUP_IDX ON ENEMDU(UPPER(SUBSTR(GRUPO_OCUPACION,6)));