CREATE TABLE MY_EMPLOYEE
  (
    ID         NUMBER(4, 0) NOT NULL ,
    LAST_NAME  VARCHAR2(25) ,
    FIRST_NAME VARCHAR2(25) ,
    USERID     VARCHAR2(20) ,
    SALARY     NUMBER(9, 2) ,
    CONSTRAINT MY_EMPLOYEE_PK PRIMARY KEY ( ID ) ENABLE
  );
