SELECT * FROM HR.JOBS;

SELECT COUNT(*) FROM HR.JOBS;

SELECT MAX(REGION_ID) FROM HR.REGIONS;

INSERT INTO HR.REGIONS VALUES (5,'Oceania');

INSERT INTO HR.REGIONS VALUES (6,'Africa');

SELECT MAX(country_id) FROM hr.countries;

SELECT * FROM HR.employees;

UPDATE HR.REGIONS SET region_name = 'ASIA' WHERE region_id = 3;