ALTER USER "HR" ACCOUNT UNLOCK;

ALTER USER "HR" IDENTIFIED BY "oracle";

CREATE USER invitado IDENTIFIED BY pwdinvitado;

GRANT CONNECT,RESOURCE TO INVITADO;

GRANT SELECT ON HR.JOBS TO INVITADO;

GRANT SELECT, INSERT ON HR.REGIONS TO INVITADO;

REVOKE INSERT ON HR.REGIONS FROM INVITADO;

CREATE ROLE RConsultaEmpleados;
GRANT CREATE SESSION, CREATE TABLE TO RConsultaEmpleados;
GRANT SELECT ON HR.ListaEmpleados TO RConsultaEmpleados;

CREATE USER ana IDENTIFIED BY ana;
CREATE USER juan IDENTIFIED BY juan;
CREATE USER pedro IDENTIFIED BY pedro;
GRANT RConsultaEmpleados TO ana;
GRANT RConsultaEmpleados TO juan;
GRANT RConsultaEmpleados TO pedro;
